version: '3.5'

services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="nest_mongo_docker"
    ports:
      - 27017:27017
    networks:
      - nestjs-task-management-backend

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-task-management
    environment:
      - NODE_ENV="production"
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules   # Add this line for volume mount

    networks:
      - nestjs-task-management-backend

networks:
  nestjs-task-management-backend:
    driver: bridge